apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: syk-dig
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 90
  port: 3000
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
    sidecar:
      enabled: true
  ingresses:
    - 'https://syk-dig.intern.nav.no'
  accessPolicy:
    outbound:
      rules:
        - application: syk-dig-backend
  env:
    - name: ASSET_PREFIX
      value: 'https://cdn.nav.no/teamsykmelding/syk-dig'
    - name: GOSYS_URL
      value: https://gosys.intern.nav.no/gosys/bruker/brukeroversikt.jsf
    - name: SYK_DIG_BACKEND_SCOPE
      value: api://prod-gcp.teamsykmelding.syk-dig-backend/.default
    - name: SYK_DIG_BACKEND_HOST
      value: syk-dig-backend
    - name: MODIACONTEXTHOLDER_SCOPE
      value: api://prod-fss.personoversikt.modiacontextholder/.default
    - name: MODIACONTEXTHOLDER_HOST
      value: modiacontextholder.prod-fss-pub.nais.io
    - name: RUNTIME_ENVIRONMENT
      value: production
