apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: syk-dig-demo
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 3000
  liveness:
    path: /api/internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /api/internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  ingresses:
    - 'https://syk-dig.ekstern.dev.nav.no/'
  env:
    - name: IS_NAIS_LABS_DEMO
      value: 'true'
    - name: RUNTIME_ENVIRONMENT
      value: demo
