apiVersion: networking.k8s.io/v1
kind: 'Ingress'
metadata:
  annotations:
    haproxy.org/backend-config-snippet: |
      http-request redirect location https://syk-dig.intern.nav.no/utenlandsk/%[url_param(oppgaveid)] code 302 if { path_reg -i ^/smd(/|$) }
      http-request redirect location https://syk-dig.intern.nav.no/nasjonal/%[url_param(oppgaveid)] code 302 if { path_reg -i ^/smr(/|$) }
      http-request redirect location https://tsm-manuell.intern.nav.no/oppgave/%[url_param(oppgaveid)] code 302 if { path_reg -i ^/smm(/|$) }
  labels:
    app: syk-dig
    team: teamsykmelding
  name: oppgaver-gosys-redirect
  namespace: teamsykmelding
spec:
  ingressClassName: internal-haproxy
  rules:
    - host: sykmelding-redirect.intern.nav.no
      http:
        paths:
          - backend:
              service:
                name: syk-dig
                port:
                  number: 80
            path: /
            pathType: Prefix
