apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: syk-dig
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 3000
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
      claims:
        extra:
          - 'NAVident'
    sidecar:
      enabled: true
  ingresses:
    - 'https://syk-dig.intern.nav.no'
  accessPolicy:
    outbound:
      rules:
        - application: syk-dig-backend
        - application: smregistrering-backend
        - application: modiacontextholder
          namespace: personoversikt
      external:
        - host: teamsykmelding-unleash-api.nav.cloud.nais.io
  env:
    - name: SYK_DIG_BACKEND_SCOPE
      value: api://prod-gcp.teamsykmelding.syk-dig-backend/.default
    - name: SYK_DIG_BACKEND_HOST
      value: syk-dig-backend
    - name: SMREGISTRERING_BACKEND_SCOPE
      value: api://prod-gcp.teamsykmelding.smregistrering-backend/.default
    - name: SMREGISTRERING_BACKEND_HOST
      value: smregistrering-backend
    - name: MODIACONTEXTHOLDER_SCOPE
      value: api://prod-gcp.personoversikt.modiacontextholder/.default
    - name: MODIACONTEXTHOLDER_HOST
      value: modiacontextholder.personoversikt
    - name: UNLEASH_SERVER_API_URL
      value: 'https://teamsykmelding-unleash-api.nav.cloud.nais.io/api'
  envFrom:
    - secret: syk-dig-unleash-secrets
