apiVersion: networking.k8s.io/v1
kind: 'Ingress'
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: https://syk-dig.intern.nav.no/oppgave/$arg_oppgaveid?
  labels:
    app: syk-dig
    team: teamsykmelding
  name: syk-dig-gosys-redirect
  namespace: teamsykmelding
spec:
  ingressClassName: nais-ingress
  rules:
    - host: sykmelding-redirect.intern.nav.no
      http:
        paths:
          - backend:
              service:
                name: syk-dig
                port:
                  number: 80
            path: /smd(/|$)(.*)
            pathType: ImplementationSpecific