name: Demo delete
on: delete

permissions:
  actions: read
  contents: read
  security-events: write
  packages: write
  id-token: write

jobs:
  branch-delete:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/next-app-demo-delete.yaml@leos-dotfolder
    secrets: inherit
    with:
      app: syk-dig
      base-path: ''
