name: Demo delete
on: delete

jobs:
  branch-delete:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/next-app-demo-delete.yaml@node-20
    secrets: inherit
    with:
      app: syk-dig
      base-path: ''
