name: Deploy smreg redirect ingress to prod
on:
  push:
    paths:
      - 'nais/redirect-prod.yaml'
      - '.github/workflows/deploy-redirect**'
    branches:
      - 'main'
jobs:
  deploy:
    if: false # Disabled until we wanna go live in production
    name: deploy redirect ingress to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy redirect ingress to prod-gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/redirect-smreg-prod.yaml
